In [1]:
import numpy as np

In [2]:
my_list1 = [2, 4, 24]
my_list2 = [3, 6, 9, 27]
multiply = []
for number1, number2 in zip(my_list1, my_list2):
    multiply.append(number1 * number2)
print(multiply)

[6, 24, 216]


In [3]:

m1 = [3, 5, 1]
m2 = [2, 1, 6]
print(np.multiply(m1, m2))

[6 5 6]


In [4]:
m1 = np.array(m1)
m2 = np.array(m2)

In [5]:
m1_matrix = np.concatenate((m1, m1, m1))

In [6]:
m1_matrix = m1_matrix.reshape(3,3)

In [7]:
m1_matrix

array([[3, 5, 1],
       [3, 5, 1],
       [3, 5, 1]])

In [8]:
m1_matrix * m2

array([[6, 5, 6],
       [6, 5, 6],
       [6, 5, 6]])

In [9]:
m1_matrix * m2.reshape((1,3))

array([[6, 5, 6],
       [6, 5, 6],
       [6, 5, 6]])

In [10]:
np.matmul(m1_matrix, m2)

array([17, 17, 17])

In [11]:
result_array = None

In [12]:
for el in m2:
    temp_array = m1 * el
    if result_array is None:
        result_array = temp_array
    else:
        result_array = np.concatenate((result_array, temp_array))

In [13]:
result_array.reshape((3,3))

array([[ 6, 10,  2],
       [ 3,  5,  1],
       [18, 30,  6]])

In [14]:
m1 = [3, 5, 1]
m2 = [2, 1, 6]

In [15]:
result_array

array([ 6, 10,  2,  3,  5,  1, 18, 30,  6])

In [16]:
np.mod(m1, 7)

array([3, 5, 1])

In [17]:
np.mod(result_array, 7)

array([6, 3, 2, 3, 5, 1, 4, 2, 6])

In [18]:
m1 * m2[2]

[3, 5, 1, 3, 5, 1, 3, 5, 1, 3, 5, 1, 3, 5, 1, 3, 5, 1]

In [20]:
powers = np.array([2,3,4,5,6])

In [24]:
2_pow = np.power(x1, x2)

SyntaxError: invalid decimal literal (1948985019.py, line 1)

In [30]:
x1 = np.arange(10)

In [28]:
x1

array([0, 1, 2, 3, 4, 5])

In [23]:
x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
np.power(x1, x2)


array([ 0.,  1.,  8., 27., 16.,  5.])

In [32]:
res = np.power(2, x1)

In [33]:
np.mod(res, 7)

array([1, 2, 4, 1, 2, 4, 1, 2, 4, 1])

In [43]:
x3 = [6, 12, 18, 19, 20]

In [44]:
res2 = np.power(3, x3)

In [45]:
np.mod(res2, 7)

array([1, 1, 1, 3, 2])

In [42]:
x4 = np.arange(10)
res3 = np.power(3, x4)
np.mod(res3, 7)

array([1, 3, 2, 6, 4, 5, 1, 3, 2, 6])

In [50]:
x5 = np.arange(20)
res4 = np.power(2, x5)
res4

array([     1,      2,      4,      8,     16,     32,     64,    128,
          256,    512,   1024,   2048,   4096,   8192,  16384,  32768,
        65536, 131072, 262144, 524288])

In [51]:
np.mod(res4, 7)

array([1, 2, 4, 1, 2, 4, 1, 2, 4, 1, 2, 4, 1, 2, 4, 1, 2, 4, 1, 2])

In [52]:
np.power(np.power(2,4), 3)

4096